### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mambasmile** [OpheliaMiralles/WindDownscaling_EPFL_UNIBE#6]
Can you share the data with me, there is a problem with the data download on the official website recently

**Comment by steidani** [comment]
Dear @mambasmile,

the Copernicus Climate Data Store (https://cds.climate.copernicus.eu/#!/home) should be running again:
https://confluence.ecmwf.int/pages/viewpage.action?pageId=278543465

Cheers,
Dani
